---
output: pdf_document
---


Organizational citizenship behaviors (OCBs) have been the focus of extensive scholarship among researchers and practitioners for more than 4 decades. Citizenship behaviors are actions conducted by employees that are discretionary and not necessarily associated with specific job requirements [@organ_organizational_1988], and they include behaviors such as helping colleagues after being asked for assistance or accommodating the work schedules of others when they request time off. Leaders put OCBs on equal footing to task performance when asked about the merits of different behaviors within their teams [@podsakoff_oxford_2018] and researchers have gone so far as to describe OCBs as critical lubricants enhancing the social machinery of organizations [@bolino_citizenship_2002; @organ_organizational_2005]. Many studies document both the positive and negative outcomes of citizenship for individuals and collectives [@bergeron_organizational_2013; @bergeron_potential_2007; @podsakoff_individual_2009; @podsakoff_organizational_2000]. 

One topic of recent interest in this literature is a pattern which has been articulated using phrases such as “extra miler” or “good soldier” [@li_achieving_2015; @methot_good_2017]. These labels refer to an employee who consistently offers more OCBs than his or her colleagues – across an unspecified amount of time, he or she is typically one of the employees offering the greatest number of OCBs – and the presumed causes of this behavior are individual characteristics. Methot et al., (2017), for instance, argue that personality traits and prosocial motives are the research-supported causes of this pattern. Stated simply, an extra miler/good soldier exhibits sustained, superior levels of OCBs due to his or her disposition or attitude [e.g., @chiaburu_five-factor_2011]. This emphasis on individual characteristics is similar to the commonly identified predictors of OCBs in general, which include one’s prosocial motives, personality, impression management, propensity to be concerned for others, job satisfaction and commitment, perceptions of trust, fit, fairness, and ostracism [@lance_ferris_being_2019; @grant_good_2009; @meglino_considering_2004; @organ_meta-analytic_1995] (**HANDBOOK: BELLAIRS; KRISTOF-BROWN; PICCOLO**) and, at the within-person level, one’s positive affect, engagement, and perceptions of justice or supervisor support [@christian2015dynamic; @dalal_within-person_2009; @glomb_doing_2011; @ilies_interactive_2006; @matta_not_2020]. Indeed, @bolino_citizenship_1999 and @bolino_citizenship_2002 state that there is a consensus that OCBs stem from dispositions, motivation, and fairness perceptions.

There are three underdeveloped areas within the research on extra milers/good soldiers that the current study attempts to address. First, one way to view this literature is from the perspective of the fundamental attribution error [@ross_getting_2001; @gilbert_correspondence_1995] such that it is driven largely by person-oriented effects and, at times, downplays the role of the situation. Relative to the person-oriented studies, comparatively little research has investigated how the observed pattern – a tendency for an employee to be among the top citizens – may be a function not only of the individual but also the interaction between that individual and his or her situation. Exceptions exist in the fit and embeddness literatures but even among these studies the emphasis is on individual perceptions [@rich_job_2010; @vogel_integrating_2009] (**job embed chapter**). Focusing on the person by situation interaction is necessary because the same individual tendencies that yield a given behavior in one situation may manifest different behavior when circumstances change. 

Second, but related to the notion of a person by situation interaction, the conversation surrounding extra milers and good soldiers is missing an appreciation of the pleas for help employees receive over time. In their cornerstone paper describing its dimensions, @smith1983organizational state that many forms of OCB occur after a stimulus that “appears to be situational, that is, someone has a problem, needs assistance, or requests a service” (p. 661). Despite this initial emphasis, Ehrhart (2018) points out that there has been little follow-up research on the nature of requests and how they inform what we know about OCBs. Requests over time are necessary to examine for several reasons. They create a baseline for employees to react to, with some employees potentially receiving many more requests than others, have the potential to change whether a given amount of help should merit the label “extra miler” or “good soldier” (the same amount of help looks different if it follows 2 versus 12 requests for assistance), and several authors [@martocchio_employee_2009] (**Eharhart handbook**) state that most acts of affiliative citizenship happen after a request to do so. Cain, Dana, and Newman [-@cain_giving_2014], for instance, argue that a substantial amount of prosocial behavior is prompted by requests from others. 

Third, just as the person-oriented effects occupy the foreground of this literature, researchers have tended to examine the systematic while neglecting the unsystematic. Moreover, researchers sometimes imply that systematic patterns – i.e., extra milers or good soldiers – cannot be produced by unsystematic causes, an idea that runs counter to the growing research on chance and random processes [@liu_good_2016]. To appreciate this assumption, it is useful to describe a study by @bolino_well_2015. These authors examine within-person variance in OCBs, depletion, and motives, and correlate the constructs over time. They motivate their study by arguing that it is unreasonable to expect (1) motives to be completely stable over time and (2) good soldiers, or employees that exhibit greater OCBs relative to their peers, to always be good. They then demonstrate that motives do show within-person variance and that they correlate with OCBs. What these authors imply is that sustained, exceptional citizenship (i.e., long-run “streakiness”) is unlikely when there is within-person instability in the variables that are assumed to cause OCBs. Said differently, when the causes are unstable (motives), the outcome must be unstable (OCB). This idea, though, contradicts what we know about stochastic (random) processes, particularly the notion that no systematic variance in the cause is required to produce what looks like long-run stability in the outcome [@henderson_long_2012]. If the cause is random and unsystematic, it is still possible – and in some cases extremely likely – that the response process contains systematic patterns in the form of long-run streaks. What this means for the citizenship literature is that it is necessary to understand the role of randomness because the core idea underlying the notions extra miler and good soldier is that employee behaviors exhibit streakiness – a pattern which we know to be a possible byproduct of chance. 

The current research reports (Figure 1) …
The current research addresses these areas by…
To make progress toward these deficiencies/areas, the current research asks how extra milers/good soldiers might be generated from the situation by person interaction…
What do I do
-	What generates extra milers. What are the causes of this behavior pattern? That is the core question. How can that behavior pattern manifest? 
I’m talking about soliticted help and an act of help in response
“Helping behavior has been identified as an important for mof citizenship behavior by virtually everyone who has worked in this area” (p. 516) (Podsakoff, MacKenzie, Paine, & Bahcrach, 2000). 
an extra miler – or the behavioral pattern in which an employee is frequently among the top citizens – may
I’m also talking about a stock of help requests. 
The key intuition is that two features of how help requests may compile over time -- inertia and randomness – interact with possible ways people respond to their stocks of help requests. 

# Theoretical Background: Person x Situation Interaction

Many theories suggest that employee behaviors are the result of a complex interaction between acting agents and their environment. Lewin's [-@lewin_field_1951] now famous assertion that behavior is a function of both persons and situations led to a flurry of personality theories examining person by situation interactions [Cognitive affective systems theory; trait activation theory; whole trait theory; @fleeson_whole_2015; @mischel_cognitive-affective_1995; @tett_situation_2000]. Murray’s system of needs, which describes internal (needs) and external (presses) causes of behavior but “above all emphasizes the interaction between the two” [@epstein_explorations_1979, p. 652], is the foundation for several need-based models such as self-determination theory [@deci_self_1980]. The notion that behavior arises from the combination of one’s tendencies and circumstances is also described in theories of self-regulation [@dawis_note_1978; @deshon_motivated_2005]. Similarly, Blumberg and Pringle [-@blumberg_missing_1982] highlight the critical importance of adding opportunities to motivation and ability as key determinants of job performance because the environment can either enable or constrain performance [@johns_advances_2018; @stewart_adaptation_2006]. In the citizenship literature, researchers have examined person by environment effects but often from the perspective of fit or compatabiltiy such that there is a perceived match between, say, one’s values and those enacted by the organization (**handbook kristoff brown**).

The current research uses Simon’s simple rules model [@simon_behavioral_1955; @deshon_clarifying_2009] as a theoretical starting point and builds from his account of the person by situation interaction. Across a number of papers, theories, and normative models [@simon_bounded_1991; @simon_rational_1956; @simon_what_1992] Simon argues that to understand the complex behavior of an agent it is necessary to describe (1) how goal-relevant objects are distributed around it and (2) the rules it uses to select courses of action. His framework suggests that the objects employees are confronted with over time combine with the mechanisms they use to select a response to yield a given behavior. The behavior that this study focuses on is the idea of a good soldier (extra miler). Applying Simon’s framework to affiliative helping suggests that, over time, an employee exhibiting extra miler behavior may arise from the combination of the requests she receives and her responses to those requests. That is, requests for assistance (situation) interact with employee reactions (person) to yield a behavioral pattern (extra milers/good soldiers). 

In the sections below, I articulate situation effects and person effects. 
PRODUCING SUSTAINED LEAD IS THE SITUATION EFFECT. I DRAW FROM PROBABILIY THEORY TO ARTICULATE THIS ASPECT.
Recall that another purpose is to counter the reasoning by bolino and suggest that causes need not be systematic. Unsystematic (i.e., random) factors can yield systematic outcomes. 

## Situation -- Requests Over Time & Sustained Lead

A request is defined as a notification to an employee that an act of assistance can be performed. Consider a few examples: A Professor receives an email from a colleague asking if she can substitute for an undergraduate course; An employee hears an announcement from a manager that volunteers are needed for an upcoming assignment; A statistician witnesses a question posted on a forum about a statistical model relevant to her expertise; A software engineer receives a pull request; An academic receives a note from a graduate student asking for a friendly review of his paper. Moreover, any agent may experience repeated prompts over the course of a week. On Monday, a Professor may receive an email asking for assistance teaching a class. On Tuesday, she receives two more emails about optional meetings in her department (attending optional meetings is one commonly studied indicator of OCB). On Wednesday, a former graduate student, who is now a faculty member at a different school, asks for a letter of recommendation. On some days the Professor has a large stock of help requests whereas on others she has few, if any.

Requests for help are related to ideas elsewhere. Entrepenaurs respond to opportunities that prompt them to enter the market [@short_concept_2010]. Employees enact job performance after being triggered by what Stewart and Nandkeolyar [-@stewart_adaptation_2006; -@stewart_exploring_2007] refer to as situation enabling factors. Safety reminders stimulate safety behaviors [@komaki_behavioral_1978]. Questions that interrupt a training intervention and prompt self-regulatory activity improve learning and performance [@sitzmann_sometimes_2010]. Prompts are also examined in selection [@levashina_structured_2014], forensic interviews [@sternberg_use_2001], and in event-sampling methodology where they are used to improve participant survey responding [@laurenceau_using_2005; @shiffman_ecological_2009]. 

What is missing in these other areas that becomes relevant as we consider requests over time is a discussion of sustained lead: some employees may consistently receive greater or fewer requests than others. The notion of sustained lead is well-known in literatures focusing on stocks other than requests [e.g., finance, strategy, mechanics; @denrell_random_2004; @henderson_long_2012; @akimoto_generalized_2008; @shreve_stochastic_2004]. It has not received attention in the citizenship space because studies do not often capture how requests compile over time (Ehrhart, 2018). Instead, most examine how to appropriately phrase a single, one-time plea [@cain_giving_2014], leaving the idea of a stockpile unspecified. An employee’s pool of requests may change or stay the same as she moves throughout her week. Due to this fluidity, the size of her pool may be larger or smaller than her colleagues. Larger on some days; smaller on others, or vice versa. Sustained lead refers to a situation in which the rank order of a set of stocks remains stable over time. Applied to help requests, this would mean that employees with the most requests at time $t$ also tend to be the employees with the most requests at $t$ + 1, $t$ + 2, and so on. It captures the stability of relative positions and it is worth considering for the following reason. If sustained lead occurs with requests, it establishes a situation where some employees continually experience more requests than others. It does not guarantee action but creates an environment with unequal opportunity. Recall that the core idea underlying extra milers/good soldiers is that some employees repeatedly exhibit more citizenship than their colleagues. Sustained lead may be one factor gently pushing in that direction. Of course, it also depends on how employees respond.

Simon’s (1955) situation by person framework suggests that the arrangement of objects in a person environment is one aspect influencing his or her behavior. In this research, I use requests over time and sustained lead to specify this broad idea. There are two schools of thought regarding the mechanisms of sustained lead: the random and the systematic. 

### The Random School of Thought

Probability theory and stochastics [@jaynes_probability_2003; @basu_introduction_2003; @levy_certains_1940] offer two features that are sufficient to yield sustained lead whenever they occur in tandem. These include inertia and randomness. 

**Inertia**. Inertia refers to the self-similarity of a variable from one moment to the next (**Cronin & Vancouver, 2020**). It can be thought of as conservation or persistence in the sense that the state retains its condition over time until something changes it. When an employee compiles help requests with inertia this means that he or she has a pool or store of help requests – three, for example – and this number is self-similar such that it carries-over from day to day. If the employee receives three help requests today, this number is added to the store of requests that she had yesterday, creating a total that moves forward into tomorrow. Similarly, when help requests are removed from the pool – which could occur, for instance, after she or someone else provides help and the request is resolved or when a deadline passes and help is no longer required – then it decreases by whatever amount was withdrawn. But removing a request does not drive the pool to zero. Instead, whatever amount was removed is subtracted from the total in such a way that the pool has inertia/memory – the amount changes from where it was at the immediately prior time point, it does not arbitrarily swing to zero. 

Weiss, H. M., & Cropanzano, R. (1996). Affective events theory: A theoretical discussion of the structure, causes, and consequences of affective experiences at work. In B. M. Staw & L. L. Cummings (Eds.), Research in organizational behavior (pp. 1–74). Greenwich, CT: Elsevier Science.

**Randomness**. The second feature is the extent to which requests compile randomly. The idea that chance has a stronger effect on people’s lives than often given credit for is expressed in social theory [@bandura_psychology_1982; @dew_serendipity_2009], probability theory and mathematics [@dobrow_introduction_2016], and among popular press [@taleb_fooled_2005; @mlodinow_drunkards_2008]. In the current research, the notion of randomness is drawn from the chance perspectives presented in @denrell_perspectivechance_2014 and @liu_good_2016. An employee that accumulates requests randomly means that the likelihood of receiving a request or having a request removed is pulled from a probability distribution such that both are equally likely. It is a coin-flip whether requests join or leave. Mathematically, an employee’s stock adds or subtracts requests based on a draw from a distribution $N(0, \sigma^2)$.

Probability theory demonstrates that a set of trajectories (e.g., requests over time for multiple employees) exhibiting both inertia and randomness generates sustained lead. In simple terms, there is a high probability that one employee will consistently have more requests than another if requests compile randomly with inertia. If inertia is not present, however, sustained lead does not occur (Table 2). 

### The Systematic School of Thought

Paste these cites from old word doc.

Other theories offer non-random sources of sustained lead. The principle of cumulative advantage [@aguinis_cumulative_2016] suggests that small benefits received during early periods fuel large gaps between “haves” and “have nots” at later stages. The mechanisms that create lasting advantages are numerous, and they include incumbency effects [@saloner_strategic_2001], path dependence (Arthur, 1989), first-mover-effects (Lieberman & Montgomery, 1988), switch costs (Klemperer, 1995), resource developments (Nelson & Winter, 1982; Dosi, 1988), lucky early detections (Barney, 1986), productivity multiplicity and ceilings (Aguinis et al., 2016), network effects (Gnutzmann, 2008), and Matthew effects (e.g., Vancouver, Li, Weinhardt, Steel, & Purl, 2016). Due to any combination of these features, employees may exhibit sustained differences in their resource pools (such as request for help). Social capital theory [@adler_social_2002; @nahapiet_social_1998; @galunic_positive_2012] also captures the idea of preserved differences in pools. Some individuals accrue large stores of social capital and are therefore differentially exposed to a whole host of aspects, some of which include information, social support, direct and indirect contacts, cutting-edge technology, trust, diverse perspectives, and unique communities [@hansen_search_1999; @inkpen_social_2005; @reinholt_central_2011; @seibert_social_2001]. Due to this exposure, then, employees with greater social capital may persistently receive greater numbers of requests than others.

Although I return to cumulative advantage and social capital in the Discussion, this research focuses largely on the random perspective for the following reasons. First, one core purpose of this study is to counter the reasoning by Bolino et al. (2015) and demonstrate that unsystematic factors can lead to systematic outcomes. As stated, their research takes the perspective that instability in the presumed causes of citizenship implies instability in citizenship itself. The current study suggests that even when an underlying cause of citizenship is unsystematic the observed behavior may still exhibit systematic patterns. Randomness is the quintessential form of an unsystematic effect, making it necessary to include in order to demonstrate this point. Second, Bandura’s theory of chance factors [-@bandura_psychology_1982] suggests that randomly occurring events often have a significant influence on behavior. This sentiment is echoed in several discussions of stochastic processes [@ross_introduction_2014; @tijms_understanding_2012]. For at least some subset of employees, the requests they receive may follow a random pattern. From a different perspective, @liu_good_2016 suggest that even when a system is non-random embedding randomness as a first principle into one’s research is necessary when the object of study – requests for help in this case – is influenced by many potentially uncontrollable forces. Help requests may come and go because of serendipity, luck, or influences that employees themselves do not cause. Moreover, the true causes of arrivals and departures may not be random at all. What @liu_good_2016 propose is that when many such effects operate on a stock then randomness can be an appropriate perspective because observed data on the stock itself will appear random. Fourth, @denrell_perspectivechance_2014 argue that randomness should be the theoretical starting point whenever research examines compiling trajectories in a new domain. Most research on compliance examines a single plea. This research, instead, takes a small step in the direction toward considering requests that compile over time. Following Denrell et al.’s (2014) recommendation, I start with randomness because little research exists on request stockpiling over time. 

The last reason is the most important: randomness can be an appropriate perspective at a given level of analysis. One component in this research is the concept of a help request trajectory: a time-series representing one’s store of requests that can fluctuate up or down at each step. Although little research exists on these specific trajectories, there is a massive literature showing that randomness may appear whenever studies examine compiling trajectories. In economics, financial and visitor arrival trajectories exhibit randomness [@cooper_world_1982; @bhattacharya_testing_2005]. In biology, foraging and movement trajectories exhibit randomness [@hill_biased_1997]. In psychology, memory search and decision trajectories exhibit randomness [@hills_optimal_2012; @reike_one_2016]. None necessarily imply a fundamentally stochastic world, only that random movement exists at the level of an observed trajectory. Many trajectories captured in time-series data manifest random patterns – the same may occur for help requests. This does not mean that if we were to zoom-in to a lower level of analysis that the elements of the system would be random. They may not be. Everything underneath could in fact be non-random. The current research, though, is at a higher level of analysis focusing on the trajectory itself. At this zoomed-out level of analysis [@zaheer_time_1999], trajectories often express random movements. That is, despite non-random origins an observed trajectory at a higher level of analysis can fluctuate randomly from one time point to the next. A pool of help requests is one such “higher level” trajectory. For this reason, randomness isn’t something to be shunned but understood. By taking the random persepctive, therefore, I am not suggesting that received help requests are fundamentally random but that random movement may exist at the level of an observed trajectory. To the extent that random fluctuations appear in data, randomness is a meaningful perspective. A pilot study reported below addresses whether there is evidence of randomness in request trajectories. 

THESE CITES ARE IN NEWER WORD DOC.

The notion that trajectories with inertia and randomness exhibit sustained lead was originally expressed using Paul Levy’s arcsine law but it is now commonly referred to as the law of long leads in random processes. Sustained leads have been examined in studies of organizational age (cite), resource accumulation (cite), and firm performance (cite). The current article continues this research by considering requests for help as stocks that may rise or fall over time, potentially exhibiting sustained lead. Of course, to determine whether extra milers/good soldiers arise it is also necessary to describe the person. 


## Person – Responding To Requests

Studies have shown that people comply with one-shot requests for many reasons. Typical effects include the attractiveness and tone of the person asking [@waddell_its_2015; @gross_beneficiary_1975; @fehr_obtaining_1979], the mood, arousal, empathy, and stereotypes of the person being asked [@paciello_high_2013; @cialdini_social_2004; @forgas_asking_1998; @florey_reactions_1997], the number of other people present [@yechiam_learning_2003; @barron_private_2002; @latane_unresponsive_1970], and the framing of the message [e.g., direct, urgent, positive, specific; @ellison_social_2014; @enzle_rhetorical_1982; @goldman_requests_1983; @graham_consultant_1998; @langer_semantics_1972]. There is less research addressing how individuals respond to a dynamic pool of requests -- i.e., reacting to received requests that continually update and may or may not compile into a large pool. To reason about this less commonly studied perspective, I draw from compliance techniques and self-regulation theory. 

**Respond to Many**. One way employees might react is that they offer greater help when request pools are large rather than small. Control theory suggests that people monitor discrepancies between current and desired states [@lord_moving_1994; @powers_feedback_1973]. At any fixed point in time, action is directed toward reducing a discrepancy such that people allocate resources until it is eliminated. When employees receive many requests for help, they may perceive a discrepancy that directs them toward action: current levels of help are not sufficient to deter incoming requests and so greater resource investments are required. With sustained lead, this type of responding would yield extra milers/good soldiers because the size of the request pool influences how individuals act. Employees with larger pools offer more help than employees with smaller pools. Moreover, relative positions of pleas persist under sustained lead. In this situation by person interaction, some employees would repeatedly offer more help than others because they continually have larger request pools. Without sustained lead (i.e., when requests compile randomly but without inertia), this type of responding would yield similar levels of help across all employees and would therefore not yield extra milers/good soldiers. 

Hypothesis 1: If requests compile with randomness and inertia and employees offer greater help when they have many rather than few requests then good soldiers emerge. 

Hypothesis 2: If requests compile with randomness but not inertia and employees offer greater help when they have many rather than few requests then good soldiers do not emerge.

**Respond to Few**. There is also theory to suggest that employees offer help when they have few rather than many requests. According to resource allocation theory [@becker_theory_1965; @hockey_compensatory_1997], people have a limited capacity to direct attention to multiple aspects of their work. With fewer requests, an employee may have more time and cognitive resources to devote to the individuals asking for help. Many employees, for instance, find that they can be more effective when demands do not stretch them too thin [@brown_attenuating_2005]. The same conclusion arises from an alternative perspective. Research on boredom [@guihyun_park_why_2019] suggests that low activity situations lead to associative thought which can prompt action. To the extent that an employee with few requests is less stimulated than an employee with many, he or she may experience greater levels of boredom which, in turn, acts as a catalyst for action. Bored employees, for instance, may become more creative [@mann_does_2014; @baird_back_2011] and effective [@gasper_approaching_2014] in their offer to help. With sustained leads, this type of responding would yield extra milers/good soldiers because help is driven once again by the size of one’s request pool. Without sustained leads, conversely, help would be similar across employees.

Hypothesis 3: If requests compile with randomness and inertia and employees offer greater help when they have few rather than many requests then good soldiers emerge. 

Hypothesis 4: If requests compile with randomness but not inertia and employees offer greater help when they have few rather than many requests then good soldiers do not emerge.

**Respond to Influx**. Employees may also respond to the number of new arrivals. A commonly studied effect in social psychology is the foot-in-the-door (FITD) technique, which is a strategy used to secure compliance [@freedman_compliance_1966]. The core idea is that a small request is immediately followed by a larger one so that the target, after being lured by the original request, responds to both. Evidence for the effectiveness of this technique is mixed [@dillard_sequential-request_1984; @weyant_application_1996]. Moreover, studies often examine a single snapshot of back-to-back requests rather than a continual influx of requests over time. In general, though, this research offers indirect support for the idea that employees may offer help when they witness an influx of requests. Research on the velocity aspect of control theory also suggests that employees may respond to the change (rather than size) of their request pool. Experiments show that information about one’s changing situation relate to affective and cognitive reactions when discrepancy sizes are held constant [@chang_moving_2009; @hsee_velocity_1991]. This type of responding would yield the same outcome with and without sustained leads. Help is based on request pool changes rather than size and so the effect of request sustained leads would be diminished.

Hypothesis 5: If requests compile with randomness and inertia and employees offer greater help when they experience an influx of requests then good soldiers do not emerge. 

Hypothesis 6: If requests compile with randomness but not inertia and employees offer greater help when they experience an influx of requests then good soldiers do not emerge.

**Respond to Outflow**. The alternative is that employees offer help when requests exit. The sibling compliance strategy to the FITD technique is the door-in-the-face (DITF) technique: start with a large request but quickly withdraw and request something smaller [@cialdini_test_1976; @cialdini_reciprocal_1975]. Evidence for this effect is also mixed but somewhat more favorable [@dillard_sequential-request_1984; @weyant_application_1996]. This technique suggests that employees may offer help when they experience requests leaving rather than arriving from their pool. Under this response, employees again react to change rather than size. The hypothesized outcome, therefore, is that good soldiers do not emerge irrespective of randomness and inertia. 

Hypothesis 7: If requests compile with randomness and inertia and employees offer greater help when they experience an outflow of requests then good soldiers do not emerge.

Hypothesis 8: If requests compile with randomness but not inertia and employees offer greater help when they experience an outflow of requests then good soldiers do not emerge.

**Norm Conformity**. A final possibility is that employees look to their colleagues to determine how much help to provide. Research on conformity suggests that people often change their behavior to match the responses of others [@cialdini_social_2004]. They do so because they desire to form an accurate interpretation of reality or to obtain social approval [@deutsch_study_1955; @pan_social_2017]. Moreover, social impact theory [@latane_psychology_1981] suggests that people conform to the attitudes, beliefs, and behavioral propensities exhibited by the people in their surroundings (although not always). Employees may therefore try to match their peers, offering help in a similar way to what they witness among their colleagues. Indeed, research suggests that perceived norms and majority tendencies relate to one’s allocation of help [@bolino_citizenship_2009; @liu_organizational_2017; @grant_give_2014]. Studies on career aspirations have also shown that individuals use group averages to compare against when forming impressions of their own achievement [@nagengast2012big]. The hypothesized outcome under this response is that extra milers/good soldiers do not emerge because employees look to others rather than requests to determine their allocation of citizenship. Note that with norm conformity it is possible for all employees to converge on a high level of citizenship yet the notion of one or few being exceptional would be absent -- no one stands out as superior if all are equally great.

Hypothesis 9: If requests compile with randomness and inertia and employees match their colleagues in how much help they provide then good soldiers do not emerge. 

Hypothesis 10: If requests compile with randomness but not inertia and employees match their colleagues in how much help they provide then good soldiers do not emerge.

# Research Overview

This research is completed in two stages. In the first, I conduct a pilot study addressing the question, Is there evidence that requests for help exhibit randomness and inertia? Although such motion is commonly identified in other time-series data, little research has examined whether help request trajectories display these features. Assessing this first question is, therefore, necessary as a preliminary step leading to the substantive hypotheses regarding good soldiers and extra milers. In the second, I develop an agent-based model to assess Hypotheses 1-10. I obtained institutional review board (IRB) approval for this research from Michigan State University (IRB number). 

# Pilot

To assess whether at least some help request trajectories exhibit random movement I collected archival data from the Internet. I followed the theory-driven web scraping approach proposed by @landers_primer_2016, which states the following. Begin with a research question already determined and then develop a scraping approach to address it (rather than the other way around); Seek data that is indicative of the target behavior; Identify how the planned analyses inform one's selection of web data; Once collected, assess whether one's assumptions about web behavior manifest in the scraped data; Articulate which assumptions were and were not met and how the data was adjusted accordingly. In this pilot study, the research question was whether help request trajectories display randomness and inertia. The planned analysis was to examine the presence or absence of these features in time-series data using unit root tests (described later) -- which require data with many time points. I therefore selected GitHub as a platform to scrape data from because it contains indicators of requests for help directed at individuals over long periods of time. 

**Issues on GitHub Repositories -- Non-Academic**. Data were collected from GitHub repositories created by software developers. GitHub is an open source website that allows users to store, manage, share, and collaborate on projects (repositories) and, although most use it for code, it can also be used for other types of documents such as Word files. The data I collected are known as repository “issues.” When an individual posts a repository/project, other users can then download and use the code that she/he created. If other users want to ask questions, request features, or report bugs, they can post an issue on the focal individual’s repository which automatically triggers a notification. The repositories I selected were posted by single users, rather than groups, to ensure that issues were targeted at one individual. Moreover, although it was possible for a single user to post and maintain more than one repository I obtained data on one repository per user. For a given repository owned by a single user, I collected all issues from when the repo was first created until the most recent post. This process was repeated for 8 different users. 

**Issues on GitHub Repositories -- Academic**. I also collected data from GitHub repositories created by academics. University faculty often use GitHub as a version control system when writing documents, as a platform to share, monitor, and adjust any applications or tools that they develop, and as a resource for downloading data science tools. Similar to above, I collected issues across 8 different repositories, each maintained by a single academic. 

For each of these 16 data sets, a help request was operationalized as an issue. For each issue, I collected (a) the date it was posted and (b) when it was removed or resolved, if ever. Issues can be removed or resolved on GitHub due any number of reasons. The individual who posts it may figure out the problem on his or her own. If this happens, he or she can follow-up the original issue with another notification. It is also possible for the repository owner to respond and then close the issue. Alternatively, a "bystander" -- someone who did not post the issue nor did he or she create the repo but happened to come across the public system of notifications for any number of reasons (one being that he or she uses the code within the repository and so actively follows it) -- can send his or her own response. For any or all of these reasons, requests can be removed/resolved. Of course, it is also possible for them to lay dormant indefinitely. Following suggestions from @landers_primer_2016, both academic and non-academic repositories were included because it is possible to view various types of repository activity either as in-role or extra-role behavior. PODSAKOFF CHAPTER also note that the boundaries of citizenship are sometimes blurry because employees may believe certain behaviors to be in-role even though they are not part of a job description (and vice versa). In my view, repository activity is clearly extra-role for an academic whereas it may or may not be for a software developer. For this reason, I saw it as important to collect data from both. Whether or not a given repository was created by an academic versus non-academic was determined by reading the user's profile. 

After scraping the raw data and prior to converting it into a time-series format for analysis the data was checked against my assumptions about its format [@landers_primer_2016]. My first assumption was that the data would offer observations frequently over long periods of time. This assumption was met (see Results for descriptives). I also assumed that repository owners would receive issues from other individuals. This assumption was partially met. I noticed that, occassionally, a repository owner would post an issue him or herself and subsequently respond -- a web behavior that I had not planned for. Out of all data points gathered, self-created issues happened 2% of the time. @landers_primer_2016 recommend selecting cases that are consistent with one's data-source theory and removing inconsistencies if they occur infrequently. Self-created issues, therefore, were not included in the final data set. Only issues posted by non-owners of the repository counted toward a help request trajectory. Keep in mind that selecting cases that are representative of one's data-source theory is different from aimlessly creating missing data [@newman_missing_2014]. 

### Analysis

The final data structure includes 16 time-series trajectories each representing the number of received help requests (issues) at a given time point for a single user. Each time-series represents a stock of help requests over time, with greater values indicating more requests and lower values indicating fewer requests. For each data set, the pilot research question regarding randomness and inertia is evaluated by assessing whether the series contained a unit root. Unit root tests examine the presence or absence of random walks in time-series. For a larger discussion of random walks see [@kuljanin_cautionary_2011]. What matters for my purposes is that random walks contain both inertia and random movement, so when a unit root test cannot reject the presence of a random walk then there is evidence that both inertia and random fluctuations occur. Two unit root tests were used. The first, the augmented Dickey-Fuller [@dickey_distribution_1979] test, is the most widely used statistic to evaluate the presence of random walks in time-series data. The null hypothesis of this test is that the data are generated from a random walk. There is also a unit root test in which the null hypothesis is instead the absence of a unit root, and the most well-known test of this second type is the @kwiatkowski1992testing statistic. Stated simply, when the ADF cannot reject its null but the KPSS can then the two fail to reject randomness and inertia. 

### Results

Number of time points. Descriptives on owners of repositories. time step of time points. Maybe plot them?

## Pilot Discussion

The pilot study reveals that at least some help request trajectories exhibit random movement. X out of Y trajectories could not reject the presence of random walks, suggesting that the time-series contained both inertia and random fluctuations. The second step in this research is to more systematically examine how dynamic requests for help interact with person responses to yield extra milers/good soldiers. 


## Study

https://erikbern.com/2019/10/16/buffet-lines-are-terrible.html

To test Hypotheses 1-10, I conduct an agent-based simulation. Agent-based models are programs written in computer code in which agents operate according to simple rules. They allow us to witness the emergence of behavioral patterns given a set of governing principles specified in a script. Prior research has used this technique to examine recruitment [@newman_recruitment_2009], firing systems and selection validity [@scullen_forced_2005], performance skews [@vancouver_using_2016], group genesis [@gray_emergence_2014], crowd behavior [@bernhardsson_buffet_nodate], how people pair with romantic partners [@kalick_matching_1986], and the effects of stereotype threat on turnover [@grand_brain_2017]. I use an agent-based model to examine whether the interaction between requests and responses induces patterns consistent with what has been described using terms such as extra milers and good soldiers. Recall that these labels refer to a subset of employees who frequently offer more help than others. It does not happen with perfect consistency, but across a window of time they are typically the employees offering the greatest amount of help. 

## Simulation Heuristic

The simulation is designed to (a) build off prior research on sustained leads in trajectories [@denrell_random_2004; @polson_good_2012] and (b) remain consistent with the idea of extra milers/good soldiers. Imagine a set of employees, each collecting help requests according to a random walk (i.e., a trajectory with randomness and inertia). From $t$ to $t + 1$, each employee retains his or her stock of help requests but the pool increases or decreases by an amount drawn from a stochastic term, meaning that the value by which it increases or decreases is random at each moment. Formally, help requests for employee $i$ at time $t$ are $x_{i_t}$ = $ax_{i-{t-1}}$ + $\varepsilon_{i_t}$, with $a = 1$ and where $\varepsilon_{i_t}$, $t$ = 1, 2, ..., $n$ are independently and identically distributed random variables with zero mean and finite variance. This simulation design is used to evaluate Hypotheses 1, 3, 5, 7, and 9, concerning trajectories with randomness and inertia. The remaining Hypotheses, concerning trajectories with randomness but not inertia, are evaluated by setting $a$ to 0. The simulation structure follows a 2x5 design, with the first factor representing the situation (random with inertia or random with no inertia) and the second representing the person (responding to many, few, influx, outflow, or conformity). Employee responses are implimented as follows.

**Responding to Many or Few**. In the first two conditions, employee help is function of the size of one's request pool. By size, I mean the number of requests that sit within an agent's stock at a given period. In the "Respond to Many" condition, employee help is a positive function of size, meaning that an employee offers more help when her request pool is large and less help when her pool is small. In the "Respond to Few" condition, employee help is a negative function size, meaning that an employee offers more help when her request pool is small and less help when her pool is large. 

**Responding to Influx or Outflow**. In the next two conditions, help is a function of request pool change. That is, employees respond based on arriving or departing requests. In the "Respond to Influx" condition, help is a function of positive change such that an employee offers help when she witnesses incoming requests but does not offer help otherwise. In the "Respond to Outflow" condition, help is a function of negative change such that an employee offers help when she witnesses departing requests but does not offer help otherwise. In both conditions, employees do not help when their pools remain identical from $t$ to $t + 1$. 

**Norm Conformity**. In the last condition, help is a function of a group average (with a given probability). After the first period, employees offer help at levels similar to their peers with probability $z$, which represents a conformity coefficient. This conformity coefficient determines the likelihood that a given employee will choose to offer help at the same level as his or her colleagues. If she chooses otherwise, then she offers help based on the size of her pool as specified in conditions 1 and 2. 

The pattern I monitor that connects to the notion of extra milers/good soldiers is the probability that a given agent starting in quantile $Q$ at time $t$ remains within +-10% of this quantile for the remaining periods. Take, for example, an employee who offers the 12th highest amount of help among a group of agents during the first step. I ask, what is the probability that she remains within a window of +-10% of that quantile in period $t + 1$? Period $t + 2$? Period $t + 3$? And so on until the last time point. For how many consecutive steps, $n$, is a given employee expected to stay within his or her same quantile? What this analysis captures is the stability of relative positions. It indicates the "streakiness" of employee help. If extra milers/good soldiers emerge, then the probability of remaining within +-10% of one's quantile should peak for large values of $n$. Said differently, if the greatest probability for a given condition is that a randomly selected employee remains within a given quantile for all periods then extra milers/good soldiers have emerged. Employees offering the most help remain so across time, as do the employees offering the least amount of help. If good soldiers do not emerge, conversely, then the greatest probability will appear over $n = 0$, meaning that there is no stability in relative positions. Employees offering the most help do not hold their first place position across time.

## Analysis & Results

Simulations were completed in Julia and are available at the following repository (www). In a single run, the number of time steps was set to 20 and the number of employees to 300. Results are based on 10,000 replicates. The design was fully crossed, with each situation factor paired with every person factor. For the conformity condition, three different values were selected for the conformity coefficient, $z$. These included 0.2 (low), 0.5 (moderate), and 0.8 (high). Conceptually, this parameter refers to the likelihood that an agent provides help consistent with norms of the other employees. Results are as follows.

**Respond to Many or Few**. Figure 1 presents the probabilty of spending $n$ time steps in the same quantile of offered help. Peak probabilities near $n = 19$ means that extra milers emerge: a given employee is most likely to spend all periods after the first step in the same relative position -- if he or she offered the 12th largest amount of help at time $t = 1$ then she offers the 12th largest amount of help thereafter. Peak probabilities near $n = 0$ indicate no good soldiers: a given employee is most likely to spend zero periods after the first step in the same relative position -- the exceptional citizens lose their rank. The first row of Figure 1 demonstrates results across the "Respond to Many" and "Respond to Few" conditions when requests move randomly with inertia. As shown, the greatest probability occurs at $n = 19$ and so good soldiers emerge. The effects are the opposite when requests compile randomly without inertia. The greatest probability occurs near $n = 0$ and so good soldiers do not emerge. Consistent with Hypotheses 1 and 2, when employees react to many rather than few requests and requests compile randomly with inertia then good soldiers emerge; they do not when requests compile randomly without inertia. Consistent with Hypotheses 3 and 4, when employees react to few rather than many requests and requests compile randomly with inertia then good soldiers emerge; they do not when requests compile randomly without inertia. 

**Respond to Influx or Outflow**. Figure 2 presents the influx and outflow conditions. As above, peak probabilities near $n = 19$ indicate extra miler emergence. In these conditions, good soldiers do not emerge irrespective of the different situation effects. The intuition for this observation is that responding to change rather than size removes the differences across the situations. Trajectories with randomness have vastly different implications for pool size depending on whether interita is or is not present. But this distinction is not relevant for arriving/departing requests -- in both, requests join or leave randomly and so they operate similarly across employees. Consistent with Hypotheses 5 and 6, when employees react to influx then good soldiers emerge regardless of randomness and inertia. Consistent with Hypotheses 7 and 8, when employees react to outflow then good soldiers also emerge regardless of randomness and inertia. 

**Norm Conformity.** Figure 3 presents the results across three different conformity values: low, moderate, and high. Extra milers emerge when conformity pressure is low and when requests compile with randomness and inertia. They are less likely to emerge when the trajectories lose inertia. At moderate conformity, extra milers are less likely to occur. And at high levels of conformity they become even less likely to occur. Consistent with Hypotheses 9 and 10, when help is based on pressures to conform rather than reacting to requests then good soldiers do not emerge (with the caveat that conformity pressure needs to be sufficiently high).

# Discussion

I conducted two studies examining a situation by person framework and its implications for the citizenship literature. The framework presented an alternative perspective on extra milers and good soldiers, which refer to employees who repeatedly offer more help than others. Results supported my Hypotheses, suggesting that alternative mechanisms can yield this streaky pattern. This research has implications for both theory and practice.

## Theoretical Implications

The present work contributes to OCB science by broadening our perspective to more readily acknowledge the role of both persons and situations. Several researchers have suggested that requests, despite being fundamental to most incidents of helping, are underexamined in the citizenship literature [@cain_giving_2014;].(**Ehrhart**) They are alive and well in related literatures such as advice and help-seeking [@bamberger_employee_2009; @bonaccio_advice_2006; @bohns_mis_2016] but are not commonly included in discussions of citizenship. The idea that requests are overlooked is matched by an emphasis in the other direction favoring individual characteristics such as motives, personality, and justice perceptions [@podsakoff_oxford_2018]. My research adds to this work by offering a situation by person framework capturing the role of requests and responses over time. I built from Simon's simple rules model and integrated notions of sustained lead, compliance, and self-regulation to articulate how frequently exceptional citizens may arise from a combination of one's circumstances and reactions. I found that, across a few different ways employees might respond to requests for help, good soldiers emerged when requests exhibited inertia and random fluctuations. These findings enhance our theoretical understanding of how the circumstances employees encounter (captured by requests over time) may combine with reactions to yield citizenship.

This research also contributes to the OCB literature because it provides mechanisms are not a priori congruent with the outcome they attempt to explain. Methot et al. (2015) argue that streaky good soldiers are due to traits such as agreeableness, proactive personality, and prosocial orientations and values. Bolino et al. (2015) provide a similar suggestion. These explanations rely on motives that in advance dispose individuals in the direction of the pattern to be explained -- a common tactit used in the social and behavioral sciences [@fiedler_beware_2000; @heider_social_1944]. As a first step in reasoning about an observed pattern, research often targets causes that are similar to or congruent with an outcome. Egocentric attributions are explained by presuming egocentric memory [@ross_egocentric_1979]. Stereotypes are explained by suggesting that stereotype-consistent information is more readily encoded, stored, and retrieved in memory [@friedrich_primary_1993; @greenberg_self_1982; @kunda_case_1990]. Similarly, a frequent helper is explained by suggesting that the individual is prosocial. My research adds to the literature regarding the causes of streaky citizenship by demonstrating how a situation by person interaction may yield this pattern. The explanation was unique because the effects did not begin with biases that push some employees toward citizenship before movement began. Extra milers emerged even though employees were homogeneous within conditions. Extra milers emerged even though the processes by which employees received help requests were identical. No a priori between-employee differences were required. This research therefore offers a unique perspective demonstrating how a seemingly systematic, between-person outcome need not require systematic, between-person causes. Of course, personality and motives matter. My intention was to present a parsimonious theoretical explanation to which such additional constructs were not strictly necessary. 

The current findings also contribute to the budding literature on chance explanations in organizational science. Several papers have recently called for a greater appreciation of randomness in organizational theory [@denrell_perspectivechance_2014; @liu_good_2016] (*dishop olenick deshon*). As stated, such a perspective does not imply that an investigated system is fundamentally random, only that this approach can be useful given the granularity of one's research. As Denrell et al. (2014) describe, "A chance explanation explains a regularity by adding the assumption of random variation and demonstrating how a mechanism involving random variation can be used to derive the regularity in question" (p.). So far, explanations using randomness as a first principle have tended to focus either on macro or cognitive applications. These include important studies on firm growth [@bottazzi_stochastic_2003; @riccaboni_size_2008], performance [@henderson_long_2012], and risk [@denrell_organizational_2008] and, at the opposite end of the spectrum, probability estimates and predictions [@hilbert_toward_2012; @falk_subjective_2009]. The findings presented here reveal how randomness may play a role in the citizenship literature. Understanding how it operates is necessary not because all acts of helping are random or because received requests are unpredictable, but because at a given level of analysis a trajectory over time may exhibit random movement. This research offers theoretical insight into the downstream consequences randomness can lead to, especially when it is paired with inertia.

It is worth reflecting on the fact that this work was different from typical presentations in organizational psychology and management. There were no regression coefficients, no multi-level models, no interviews or surveys. Instead, this research was consistent with a generative or computational perspective, or what is sometimes called the third scientific discipline [@hulin_introduction_2000]. A generative explanation describes a social phenomenon in terms of the internal and external mechanisms that may produce it, rather than by inferring causes from observed co-variations [@smith_agent_2007]. The goals of a computational approach are many: identify mechanisms that can generate a pattern of interest, suggest alternatives to previously agreed-upon predictors, call attention to variables whose importance might not otherwise be recognized, demonstrate how complexity can emerge from simple components [@epstein_model_2008]. It focuses less on prediction and more on the logic of an explanation. It tries not to fully represent the real world but abstract to something simple in order to provide insight. It eschews ambiguous language in favor of reproducible code, but at the cost of breadth. Theorists have called for researchers to use the approach [@smaldino_theory_2015] but it is far from common in organizational psychology and behavior. This work is a small step in that direction. Without such an approach, it is harder to recognize alternative mechanisms because the dynamics of a system are not easily simulated in one's head [@cronin_don_2009]. Moreover, researchers are forced to study only that which can be measured and analyzed under the covariation paradigm, naturally limiting our ability to generate theoretical insight.

Finally, the perspective presented in this research, although random, need not be incompatible with theories of cumulative advantage or social capital. The level of analysis in this study was simply one step removed. 


Cumulative advantage and social capital offer reasons for why some individuals may continually experience greater or fewer requests than others. But given differences in requests, the predictions stemming from either literature would be consistent with what was presented here. Moreover, cumulative advantage and social capital could both occur and yet an observed trajectory could exhibit random movement. 



potentially different reasons

existence of differences in requests. given that effect, they make the same prediction. Predictions from either literature would be identical to Hypotheses 1, 3, 5, 7, and 9. 


this study's level of analysis was one step removed

lower level elements may be non-random, yet request pool movement exhibits chance fluctuations
the predictions from cum & s are the same

whether the world is fundamentally stochastic or systematic is not the question this research was interested in addressing. If chance movement occurs on requests, this is what can happen
whether that random movement is due to true randomness or something like cumulative advantrage or social capital that then generated chance movement is an entirely different question.

Cumulative advantage. Social capital. Make the same predictions. Cumulative leads on requests may be due to a different reason. Those perspectives are compatible. They make the same prediction. 

## Practical implications

There are two practical implications. The first is that managers need to be weary of attributing motive after witnessing patterns of citizenship. Given the possibility of long leads from the processes described in this research, presuming that a frequent citizen has prosocial motives or characteristics may be misleading. Even if there are no systematic differences across individuals in motive or personality, there will often still be different patterns of behavior. The reverse is also true: employees exhibiting the same level of citizenship will not necessarily have the same motives. The importance of understanding this insight can be expressed using Grant's [-@grant2014give] book on helping. In it, he describes a study by @hui_instrumentalHui_2000, which examines employee citizenship before and after a promotion opportunity. The researchers find that some employees exhibit lower OCBs after being promoted whereas others retain high levels of OCBs before and after promotion. Grant (2014) explains:

>> Of the seventy tellers who were promoted, thirty-three were genuine givers: they sustained their giving after the promotion. The other thirty-seven tellers declined rapidly in their giving. They were fakers: in the three months before the promotion, they knew they were being watched, so they went out of their way to help others. But after they got promoted, they reduced their giving by an average of 23 percent each. p. 246

His description infers motive from behavior: some employees were genuine because they exhibited one pattern of citizenship whereas others were not because they exhibited a different pattern. In other words, when an employee lowered her citizenship from one period to the next she was classified as fake. The point Grant was making in his book, which I agree with, was that motives are necessary to account for, otherwise unexpected changes in citizenship can occur. Indeed, perceptions of instrumentality were an important aspect to Hui et al.'s research. My point is that drawing meaning from observed citizenship patterns, be they stable or volatile, is much harder than given credit for -- especially when only two time points are assessed. Managers need to be aware that seemingly meaningful patterns can be generated by unsystematic causes. This idea of course connects to a long history of research on attributions. Citizenship relates to supervisor impressions, liking, and attributions of motive which then relate to performance judgments [@allen_effects_1998]. Performance judgments are themselves subject to a menu of effects, including gain or loss framing, decoys, dilution, anchoring, and the correspondence principle [@gilbert_correspondence_1995; @wong_between_2005; @connolly_regret_2013; @highhouse_context_1996; @thorsteinson_anchoring_2008]. There are also studies examining how supervisors rate trajectories, often finding that the within-person mean, trend, and variability influence ratings [@ferris_goes_2018]. What this study adds to this conversation is a probabilty theory perspective: whereas performance management literatures tend to focus the extent to which supervisor ratings are more favorable given one trajectory or another [@highhouse_judgment_2013], probability theory researchers often spend considerable time trying to understand whether a given trajectory can be meaningfully parsed from chance in the first place. Such a simple effort is not without its consequences. In Hollywood, executives are evaluated based on the assumption that meaning can be culled from the random spikes and dips in box-office movie performance. Sherry Lansing, who was initially praised for successfully running the Paramount Motion Picture Group, was removed after the company's percentage-of-market-share demonstrated the following decreasing trend over six years: 11.4, 10.6, 11.3, 7.4, 7.1, 6.7 – a streak which caused BusinessWeek to state that Lansing "may simply no longer have Hollywood's hot hand" (Grover, 2003). In hindsight, researchers have argued that this sequence was far too short to adequately distinguish flawed decision-making from random fluctuations, a statement supported by follow up data demonstrating that the trajectory reverted back to its mean (Mlodinow, 2009). So it is with citizenship: managers need to be armed with the tools necessary to differentiate meaning from chance because employees who are identical in character may nonetheless exhibit different patterns of citizenship. For a greater discussion, see Henderson. 

This work also offers direction for organizations implementing helping interventions. Many strategies exist, including helping skills techniques [@hill_helping_2008], the helpful organizational behavior paradigm [@bandura_helping_2012], manager-directed initiatives [@tews_helping_2009], mentor or peer-based efforts [@hill_narrative_2006], or interventions based on the mutual-investment model [@van_employee_2018]. Organizations hoping to promote certain outcomes may want to take heed of the fact that the type of citizenship response employees enact informs the outcome that occurs across the collective. Organizations will need to consider whether they value similar or dissimilar levels of help across employees, the type of responding a given intervention calls for, the nature of requests employees experience, and the extent to which a suggested intervention will promote the outcome of interest. If an intervention, for example, promotes citizenship such that employees respond to request size rather than change then it will be much more difficult for the organization to create similar levels of citizenship across the collective. Employees may also benefit from a systematic assessment that provides feedback on how they receive variations in requests over time. Based on such detailed feedback, employees could identify their own response patterns, compare to others, and adjust accordingly in-line with espoused values of the organization. 



## limitations and future directions

Conformity
- match level of help. Match in their percent of requests that they respond to

